hugoblox:
  schema: "2.0"
  identity:
    name: Tak Ming Wong
    type: person
    tagline: Visual Computing Researcher | AI for Science | Helmholtz-Zentrum Hereon
    description: Dr. Tak Ming Wong is a scientist at Helmholtz-Zentrum Hereon. His interests are computational imaging, computer vision, DL/AI and related applications.
    organization: Helmholtz-Zentrum Hereon
  theme:
    mode: light
    pack: minimal
    colors:
      primary: "blue"
      secondary: "yellow"
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar-simple
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  analytics:
    google:
      measurement_id: G-1RR4M2KY9D
